name: control_train_only
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
  - pip:
    - opencv-contrib-python==4.3.0.36
    - pytorch-lightning==1.5.0
    - omegaconf==2.1.1
    - einops==0.3.0
    - transformers==4.19.2
    - open_clip_torch==2.0.2
    - safetensors==0.2.7
